### ISSUE TITLE
deploy script should ignore backup files

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beaker-notebook-www#135]
files like should not be uploaded

    create mode 100644 templates/community.jade~

**Comment by scottdraves** [comment]
https://github.com/twosigma/beaker-notebook-www/blob/gh-pages/templates/community.jade~

**Comment by sethkrasnianski** [comment]
Are you manually removing these files currently?

**Comment by scottdraves** [comment]
no they get published

**Comment by sethkrasnianski** [comment]
are we actually using [ship](https://www.npmjs.com/package/ship)? I see a `ship.conf` in the `.gitignore` as well as a line to remove it in the deploy script. But the fact that we're using a deploy script suggests that we're not.
