### ISSUE TITLE
Add "Beaker Lab" section to getting started

### ISSUE THREAD

**Issue by melmac48** [twosigma/beaker-notebook-www#158]
On the Getting started page, under Choose your platform, add:

Beaker Notebook can be run in the cloud through [link: Beaker Lab]. You can create an account for free and will be able to start developing in Beaker Notebook immediately.

**Comment by scottdraves** [comment]
https://github.com/twosigma/beaker-notebook-www/commit/89c4ecc6e107a4bea2e61a26c6cfa49635e431b7
