### ISSUE TITLE
Incorrect hover state

### ISSUE THREAD

**Issue by bradicdesign** [twosigma/beaker-notebook-www#96]
The dialog subscribe button should be either gray with blue hover or just blue.
![screen shot 2014-10-01 at 1 34 44 pm](https://cloud.githubusercontent.com/assets/6478279/4482632/8819a4e4-49aa-11e4-94b4-b65a6a017ec1.png)
![screen shot 2014-10-01 at 1 34 39 pm](https://cloud.githubusercontent.com/assets/6478279/4482631/8816ba7c-49aa-11e4-837a-a95d2ae31193.png)

**Comment by scottdraves** [comment]
it's just blue now
